MAP_LABELS = {
    'Water'   : 0,
    'Normal'  : 1,
    'Grass'   : 2,
    'Bug'     : 3,
    'Fire'    : 4,
    'Psychic' : 5,
    'Rock'    : 6,
    'Electric': 7,
    'Poison'  : 8,
    'Ground'  : 9,
    'Fighting': 10,
    'Dark'    : 11,
    'Ghost'   : 12,
    'Dragon'  : 13,
    'Steel'   : 14,
    'Ice'     : 15,
    'Fairy'   : 16,
    'Flying'  : 17,
    'NaN'     : 18,
}

MAP_LABELS_INV = {
    0  : 'Water',
    1  : 'Normal',
    2  : 'Grass',
    3  : 'Bug',
    4  : 'Fire',
    5  : 'Psychic',
    6  : 'Rock',
    7  : 'Electric',
    8  : 'Poison',
    9  : 'Ground',
    10 : 'Fighting',
    11 : 'Dark',
    12 : 'Ghost',
    13 : 'Dragon',
    14 : 'Steel',
    15 : 'Ice',
    16 : 'Fairy',
    17 : 'Flying',
    18 : 'NaN',
}

NUM_CLASSES = 19